const numberButtons = document.querySelectorAll("[number]")
const operationButtons = document.querySelectorAll("[operation]")
const clearButton = document.querySelector("[all-clear]")
const deleteButton = document.querySelector("[delete]")
const equalsButton = document.querySelector("[equals]")
const typed = document.querySelector("[typed]")
const typing = document.querySelector("[typing]")